export enum EN_messages {
    passwords_notFetch = 'تعداد ارقام گذرواژه با تایید آن برابر نیست',
    password_notExactly = 'گذرواژه با تایید آن یکی باید باشد',
    sameLength_eshterak = 'تعداد ارقام از اشتراک، تا اشتراک باید برابر باشد',
    format_invalid_esterak = 'فرمت اشتراک ناصحیح است',
    format_invalid_from_esterak = 'فرمت از اشتراک ناصحیح است',
    format_invalid_to_esterak = 'فرمت  تا اشتراک ناصحیح است',
    lessThan_eshterak = 'از اشتراک کمتر از تا اشتراک است!',
    percent_pictures = 'درصد تصویر نمیتواند بیش تر از 100 و کمتر از 0 باشد',
    thereis_no_reader = 'ماموری در این ناحیه انتخاب نشده است',
    not_found_period = 'مدت دوره‌ای پیدا نشد',
    thereis_no_default = 'تنظیمات قرائت پیشفرضی وجود ندارد',
    thereis_no_type = 'نوع دوره ای وجود ندارد',
    not_found_zoneId = 'ناحیه ای تعریف نشده است',
    try_again = 'یکبار دیگر مقادیر را وارد نمایید',
    notFound = 'موردی یافت نشد',
    notFoundToExport = 'موردی برای ذخیره وجود ندارد',
    highLow100 = 'مقدار نمیتواند بیش تر از 100 و کمتر از 0 باشد',
    userPass_empty = 'نام کاربری یا گذرواژه نمیتواند خالی باشد',
    access_denied = 'شما به این بخش دسترسی ندارید',
    insert_without_decimal = 'شماره نسخه را بدون اعشار وارد نمایید',
    insert_reading_time = 'مدت قرائتی ایجاد و سپس امتحان نمایید',
    insert_reader = 'یک مامور انتخاب نمایید',
    insert_karbaricode = 'کد کاربری را وارد نمایید',
    insert_karbari = 'نام کاربری را وارد نمایید',
    insert_password = 'گذرواژه را وارد نمایید',
    insert_confirm_pass = 'تکرار گذرواژه را وارد نمایید',
    insert_name = 'نام را وارد نمایید',
    insert_surename = 'نام خانوادگی را وارد نمایید',
    insert_mobile = 'شماره موبایل را وارد نمایید',
    insert_showName = 'نام قابل نمایش را وارد نمایید',
    insert_work = 'خدمتی را مشخص نمایید',
    accedd_denied_relogin = 'دسترسی شما باطل شده است. مجددا وارد شوید',
    insert_roleAccess = 'سطح دسترسی به ناحیه ای را انتخاب نمایید',
    insert_group_access = 'گروه دسترسی را مشخص نمایید',
    insert_again = 'مجددا مقادیر را وارد نمایید',
    insert_fromDate = 'از تاریخ خالی است',
    insert_toDate = 'تا تاریخ خالی است',
    insert_readingPeriod = 'دوره قرائت را وارد نمایید',
    insert_year = 'سالی وارد نمایید',
    insert_zone = 'ناحیه ای وارد نمایید',
    insert_counterState = 'وضعیت کنتور را مشخص نمایید',
    insert_desc = 'توضیحی وارد نمایید',

    allowed_forbiddenByDate = 'مشاهده غیر مجاز تنها با تاریخ امکان پذیر است',
    allowed_empty = 'مقادیر نمیتواند خالی باشند',

}
