export enum ENReadingReports {
    master = 'masterReq',
    inState = 'inStateReq',
    details = 'detailsReq',
    userKarkardReq = 'userKarkardReq',
    traverse = 'traverseReq',
    trvch = 'trvchReq',
    karkard = 'karkardReq',
    Locked = 'lockedReq',
    preNumShown = 'preNumberShownReq',
    offloadKarkard = 'karkardOffloadReq',
    karkardDaily = 'karkardDailyReq',
    gis = 'gisReq',
    dh = 'disposalhoursReq',
    anlzPrfm = 'anlzPrfmReq',
    imgAttrResult = 'imgAttrResultReq',
    imgAttrAnalyze = 'imgAttrAnalyzeReq',
}