export enum ENReadingReports {
    master = 'masterReq',
    inState = 'inStateReq',
    details = 'detailsReq',
    userKarkardReq = 'userKarkardReq',
    traverse = 'traverseReq',
    trvch = 'trvchReq',
    karkard = 'karkardReq',
    karkardAllStates = 'offKarkardAllStatesReq',
    Locked = 'lockedReq',
    preNumShown = 'preNumberShownReq',
    offloadKarkard = 'karkardOffloadReq',
    fragmentKarkard = 'rrFragmentKarkardReq',
    karkardDaily = 'karkardDailyReq',
    gis = 'gisReq',
    dh = 'disposalhoursReq',
    anlzPrfm = 'anlzPrfmReq',
    imgAttrResult = 'imgAttrResultReq',
    imgAttrAnalyze = 'imgAttrAnalyzeReq',
    imgResultDetailsGridBased = 'imgResultDetailsGridBased',
    userActivationLog = 'saveDataForServerUserActivationReq',
    usersLogins = 'usersLoginsReq',
}
