// name of the ENReadingReports should be exactly the same with usable name of variable(usually in column manager)
export enum ENReadingReports {
    master = 'masterReq',
    inState = 'inStateReq',
    details = 'detailsReq',
    guildsWithParams = 'guildsWithParamsReq',
    userKarkardReq = 'userKarkardReq',
    traverse = 'traverseReq',
    trvch = 'trvchReq',
    karkard = 'karkardReq',
    karkardAllStates = 'offKarkardAllStatesReq',
    Locked = 'lockedReq',
    dataMining = 'dataMiningReq',
    preNumShown = 'preNumberShownReq',
    offloadKarkard = 'karkardOffloadReq',
    fragmentKarkard = 'rrFragmentKarkardReq',
    karkardDaily = 'karkardDailyReq',
    gis = 'gisReq',
    dh = 'disposalhoursReq',
    anlzPrfm = 'anlzPrfmReq',
    getUploadedReq = 'getUploadedReq',
    imgAttrResult = 'imgAttrResultReq',
    imgAttrAnalyze = 'imgAttrAnalyzeReq',
    imgResultDetailsGridBased = 'imgResultDetailsGridBased',
    userActivationLog = 'saveDataForServerUserActivationReq',
    usersLogins = 'usersLoginsReq',
    ipFilterGetBlocked = 'ipFilterGetBlockedReq',
    notificationListByDateReq = 'notificationListByDateReq',
    downloadAttemptsReq = 'downloadAttemptsReq',
    uploadAttemptsReq = 'uploadAttemptsReq',
    feedbackAllCReq = 'mobileManagerFeedbackAllCReq',
    feedbackAllSReq = 'mobileManagerFeedbackAllSReq',
    forbidden = 'forbiddenReq',
    forbiddenTypeReq = 'mobileManagerforbiddenTypeReq',
}
