import { Theme } from 'interfaces/istyles';

export const fontXXS: Theme = {
    name: "fontXXS",
    properties: {
        "--font_01": "0.080rem",
        "--font_02": "0.085rem",
        "--font_025": "0.090rem",
        "--font_03": "0.1rem",
        "--font_05": "0.2rem",
        "--font_xxs": "0.25rem",
        "--font_xs": "0.3rem",
        "--font_ss": "0.7rem",
        "--font_s": "0.87rem",
        "--font_m": "1rem",
        "--font_m2": "1.1rem",
        "--font_l": "1.2rem",
        "--font_l2": "1.3rem",
        "--font_2": "1.4rem",
        "--font_22": "1.5rem",
        "--font_23": "1.6rem",
        "--font_25": "2rem",
        "--font_26": "2.15rem",
        "--font_28": "2.3rem",
        "--font_3": "2.5rem",
        "--font_33": "2.6rem",
        "--font_35": "2.8rem",
        "--font_335": "3rem",
        "--font_45": "3.3rem",
        "--font_5": "3.5rem",
        "--font_52": "3.35rem",
        "--font_55": "4.5rem",
    }
}
export const fontXS: Theme = {
    name: "fontXS",
    properties: {
        "--font_01": "0.085rem",
        "--font_02": "0.090rem",
        "--font_025": "0.1rem",
        "--font_03": "0.2rem",
        "--font_05": "0.25rem",
        "--font_xxs": "0.3rem",
        "--font_xs": "0.5rem",
        "--font_ss": "0.87rem",
        "--font_s": "1rem",
        "--font_m": "1.1rem",
        "--font_m2": "1.2rem",
        "--font_l": "1.3rem",
        "--font_l2": "1.4rem",
        "--font_2": "1.5rem",
        "--font_22": "1.6rem",
        "--font_23": "2rem",
        "--font_25": "2.2rem",
        "--font_26": "2.3rem",
        "--font_28": "2.5rem",
        "--font_3": "2.6rem",
        "--font_33": "2.8rem",
        "--font_35": "3rem",
        "--font_335": "3.3rem",
        "--font_45": "3.5rem",
        "--font_5": "4rem",
        "--font_52": "4.5rem",
        "--font_55": "5rem",
    }
}
export const fontSM: Theme = {
    name: "fontSM",
    properties: {
        "--font_01": "0.090rem",
        "--font_02": "0.1rem",
        "--font_025": "0.2rem",
        "--font_03": "0.25rem",
        "--font_05": "0.3rem",
        "--font_xxs": "0.5rem",
        "--font_xs": "0.87rem",
        "--font_ss": "1rem",
        "--font_s": "1.1rem",
        "--font_m": "1.2rem",
        "--font_m2": "1.3rem",
        "--font_l": "1.4rem",
        "--font_l2": "1.5rem",
        "--font_2": "1.6rem",
        "--font_22": "2rem",
        "--font_23": "2.2rem",
        "--font_25": "2.3rem",
        "--font_26": "2.4rem",
        "--font_28": "2.6rem",
        "--font_3": "2.8rem",
        "--font_33": "3rem",
        "--font_35": "3.3rem",
        "--font_335": "3.5rem",
        "--font_45": "3.35rem",
        "--font_5": "4.5rem",
        "--font_52": "5rem",
        "--font_55": "5.2rem",
    }
};
export const fontS: Theme = {
    name: "fontS",
    properties: {
        "--font_01": "0.1rem",
        "--font_02": "0.2rem",
        "--font_025": "0.25rem",
        "--font_03": "0.3rem",
        "--font_05": "0.5rem",
        "--font_xxs": "0.87rem",
        "--font_xs": "1rem",
        "--font_ss": "1.1rem",
        "--font_s": "1.2rem",
        "--font_m": "1.3rem",
        "--font_m2": "1.4rem",
        "--font_l": "1.5rem",
        "--font_l2": "1.6rem",
        "--font_2": "2rem",
        "--font_22": "2.2rem",
        "--font_23": "2.3rem",
        "--font_25": "2.5rem",
        "--font_26": "2.6rem",
        "--font_28": "2.8rem",
        "--font_3": "3rem",
        "--font_33": "3.3rem",
        "--font_35": "3.5rem",
        "--font_335": "3.35rem",
        "--font_45": "4.5rem",
        "--font_5": "5rem",
        "--font_52": "5.2rem",
        "--font_55": "5.5rem",
    }
};

export const FontFamilyBLotus: Theme = {
    name: "BLotus",
    properties: {
        "--font-family": "BLotus",
    }
}
export const FontFamilyBKoodak: Theme = {
    name: "BKoodak",
    properties: {
        "--font-family": "BKoodak",
    }
}