import {
    aboutUs,
    BrowserVersions,
    defaultAggregateTracks,
    ENActivateProvinceTitle,
    ENHasCancelableSpinner,
    ENHasNextBazdid,
    ENMapCenter,
    ENMapUrls,
    ENURLs,
    ENYears,
    getDeleteDictionary,
    getHighLowStateId,
    getInvalidLoginReasonDictionary,
    getLogoutReasonDictionary,
    getMasrafStateDictionary,
    getOfferingIds,
    getRequestDraftIds,
    getTarrifCalculationModeDictionary,    
    IENV,
    IENV_BROWSER_SETUP,
    NotificationAlertTypesIds,
    NotificationAlertTypesList,
    NotificationMediaTypeIds,
    NotificationMediaTypeList,
    reorderableTable,
    shouldSaveTokensInLocal,
    simafaImportStatus,
    timeout,
} from 'interfaces/build';

import { version } from '../interfaces/build';

export class ActivatedProvince implements IENV {
    public static readonly LOCAL = new ActivatedProvince(
        ENActivateProvinceTitle.LOCAL,
        ENURLs.LOCAL,
        ENMapUrls.DEFAULT.value,
        ENHasNextBazdid.DEFAULT.value,
        reorderableTable.DEFAULT.value,
        defaultAggregateTracks.DEFAULT.value,
        ENMapCenter.DEFAULT.value,
        BrowserVersions.DEFAULT.value,
        ENYears.DEFAULT.value,
        getDeleteDictionary.DEFAULT.value,
        ENHasCancelableSpinner.DEFAULT.value,
        simafaImportStatus.simafaImportStatus,
        timeout.time,
        version.version,
        aboutUs,
        NotificationMediaTypeList.DEFAULT.value,
        NotificationAlertTypesList.DEFAULT.value,
        NotificationMediaTypeIds,
        NotificationAlertTypesIds,
        getLogoutReasonDictionary.DEFAULT.value,
        getInvalidLoginReasonDictionary.DEFAULT.value,
        shouldSaveTokensInLocal.DEFAULT.value,
        getMasrafStateDictionary.DEFAULT.value,
        getHighLowStateId.DEFAULT.value,        
        getTarrifCalculationModeDictionary.DEFAULT.value,
        getRequestDraftIds,
        getOfferingIds,
    );
    public static readonly DEFAULT = new ActivatedProvince(
        ENActivateProvinceTitle.DEFAULT,
        ENURLs.DEFAULT,
        ENMapUrls.DEFAULT.value,
        ENHasNextBazdid.DEFAULT.value,
        reorderableTable.DEFAULT.value,
        defaultAggregateTracks.DEFAULT.value,
        ENMapCenter.DEFAULT.value,
        BrowserVersions.DEFAULT.value,
        ENYears.DEFAULT.value,
        getDeleteDictionary.DEFAULT.value,
        ENHasCancelableSpinner.DEFAULT.value,
        simafaImportStatus.simafaImportStatus,
        timeout.time,
        version.version,
        aboutUs,
        NotificationMediaTypeList.DEFAULT.value,
        NotificationAlertTypesList.DEFAULT.value,
        NotificationMediaTypeIds,
        NotificationAlertTypesIds,
        getLogoutReasonDictionary.DEFAULT.value,
        getInvalidLoginReasonDictionary.DEFAULT.value,
        shouldSaveTokensInLocal.DEFAULT.value,
        getMasrafStateDictionary.DEFAULT.value,
        getHighLowStateId.DEFAULT.value,        
        getTarrifCalculationModeDictionary.DEFAULT.value,
        getRequestDraftIds,
        getOfferingIds,
    );
    public static readonly RDPServer = new ActivatedProvince(
        ENActivateProvinceTitle.RDPServer,
        ENURLs.RDPServer,
        ENMapUrls.DEFAULT.value,
        ENHasNextBazdid.DEFAULT.value,
        reorderableTable.DEFAULT.value,
        defaultAggregateTracks.DEFAULT.value,
        ENMapCenter.DEFAULT.value,
        BrowserVersions.DEFAULT.value,
        ENYears.DEFAULT.value,
        getDeleteDictionary.DEFAULT.value,
        ENHasCancelableSpinner.DEFAULT.value,
        simafaImportStatus.simafaImportStatus,
        timeout.time,
        version.version,
        aboutUs,
        NotificationMediaTypeList.DEFAULT.value,
        NotificationAlertTypesList.DEFAULT.value,
        NotificationMediaTypeIds,
        NotificationAlertTypesIds,
        getLogoutReasonDictionary.DEFAULT.value,
        getInvalidLoginReasonDictionary.DEFAULT.value,
        shouldSaveTokensInLocal.DEFAULT.value,
        getMasrafStateDictionary.DEFAULT.value,
        getHighLowStateId.DEFAULT.value,        
        getTarrifCalculationModeDictionary.DEFAULT.value,
        getRequestDraftIds,
        getOfferingIds,
    );
    public static readonly ESF = new ActivatedProvince(
        ENActivateProvinceTitle.ESF,
        ENURLs.ESF,
        ENMapUrls.ESF.value,
        ENHasNextBazdid.ESF.value,
        reorderableTable.DEFAULT.value,
        defaultAggregateTracks.DEFAULT.value,
        ENMapCenter.ESF.value,
        BrowserVersions.DEFAULT.value,
        ENYears.DEFAULT.value,
        getDeleteDictionary.DEFAULT.value,
        ENHasCancelableSpinner.DEFAULT.value,
        simafaImportStatus.simafaImportStatus,
        timeout.time,
        version.version,
        aboutUs,
        NotificationAlertTypesList.DEFAULT.value,
        NotificationMediaTypeList.DEFAULT.value,
        NotificationMediaTypeIds,
        NotificationAlertTypesIds,
        getLogoutReasonDictionary.DEFAULT.value,
        getInvalidLoginReasonDictionary.DEFAULT.value,
        shouldSaveTokensInLocal.DEFAULT.value,
        getMasrafStateDictionary.DEFAULT.value,
        getHighLowStateId.DEFAULT.value,        
        getTarrifCalculationModeDictionary.DEFAULT.value,
        getRequestDraftIds,
        getOfferingIds,
    );
    public static readonly TEH = new ActivatedProvince(
        ENActivateProvinceTitle.TEH,
        ENURLs.TEH,
        ENMapUrls.TEH.value,
        ENHasNextBazdid.TEH.value,
        reorderableTable.DEFAULT.value,
        defaultAggregateTracks.DEFAULT.value,
        ENMapCenter.TEH.value,
        BrowserVersions.DEFAULT.value,
        ENYears.DEFAULT.value,
        getDeleteDictionary.DEFAULT.value,
        ENHasCancelableSpinner.DEFAULT.value,
        simafaImportStatus.simafaImportStatus,
        timeout.time,
        version.version,
        aboutUs,
        NotificationAlertTypesList.DEFAULT.value,
        NotificationMediaTypeList.DEFAULT.value,
        NotificationMediaTypeIds,
        NotificationAlertTypesIds,
        getLogoutReasonDictionary.DEFAULT.value,
        getInvalidLoginReasonDictionary.DEFAULT.value,
        shouldSaveTokensInLocal.DEFAULT.value,
        getMasrafStateDictionary.DEFAULT.value,
        getHighLowStateId.DEFAULT.value,        
        getTarrifCalculationModeDictionary.DEFAULT.value,
        getRequestDraftIds,
        getOfferingIds,
    );
    public static readonly TEH_ZONE4 = new ActivatedProvince(
        ENActivateProvinceTitle.TEH_ZONE4,
        ENURLs.TEH_ZONE4,
        ENMapUrls.TEH_ZONE4.value,
        ENHasNextBazdid.TEH_ZONE4.value,
        reorderableTable.DEFAULT.value,
        defaultAggregateTracks.DEFAULT.value,
        ENMapCenter.TEH_ZONE4.value,
        BrowserVersions.DEFAULT.value,
        ENYears.DEFAULT.value,
        getDeleteDictionary.DEFAULT.value,
        ENHasCancelableSpinner.DEFAULT.value,
        simafaImportStatus.simafaImportStatus,
        timeout.time,
        version.version,
        aboutUs,
        NotificationAlertTypesList.DEFAULT.value,
        NotificationMediaTypeList.DEFAULT.value,
        NotificationMediaTypeIds,
        NotificationAlertTypesIds,
        getLogoutReasonDictionary.DEFAULT.value,
        getInvalidLoginReasonDictionary.DEFAULT.value,
        shouldSaveTokensInLocal.DEFAULT.value,
        getMasrafStateDictionary.DEFAULT.value,
        getHighLowStateId.DEFAULT.value,        
        getTarrifCalculationModeDictionary.DEFAULT.value,
        getRequestDraftIds,
        getOfferingIds,
    );
    public static readonly TEH_SE = new ActivatedProvince(
        ENActivateProvinceTitle.TEH_SE,
        ENURLs.TEH_SE,
        ENMapUrls.TEH_SE.value,
        ENHasNextBazdid.TEH_SE.value,
        reorderableTable.DEFAULT.value,
        defaultAggregateTracks.DEFAULT.value,
        ENMapCenter.TEH_SE.value,
        BrowserVersions.DEFAULT.value,
        ENYears.DEFAULT.value,
        getDeleteDictionary.DEFAULT.value,
        ENHasCancelableSpinner.DEFAULT.value,
        simafaImportStatus.simafaImportStatus,
        timeout.time,
        version.version,
        aboutUs,
        NotificationAlertTypesList.DEFAULT.value,
        NotificationMediaTypeList.DEFAULT.value,
        NotificationMediaTypeIds,
        NotificationAlertTypesIds,
        getLogoutReasonDictionary.DEFAULT.value,
        getInvalidLoginReasonDictionary.DEFAULT.value,
        shouldSaveTokensInLocal.DEFAULT.value,
        getMasrafStateDictionary.DEFAULT.value,
        getHighLowStateId.DEFAULT.value,        
        getTarrifCalculationModeDictionary.DEFAULT.value,
        getRequestDraftIds,
        getOfferingIds,
    );
    public static readonly TEH_SE_LOCAL = new ActivatedProvince(
        ENActivateProvinceTitle.TEH_SE_LOCAL,
        ENURLs.TEH_SE_LOCAL,
        ENMapUrls.TEH_SE_LOCAL.value,
        ENHasNextBazdid.TEH_SE_LOCAL.value,
        reorderableTable.DEFAULT.value,
        defaultAggregateTracks.DEFAULT.value,
        ENMapCenter.TEH_SE_LOCAL.value,
        BrowserVersions.DEFAULT.value,
        ENYears.DEFAULT.value,
        getDeleteDictionary.DEFAULT.value,
        ENHasCancelableSpinner.DEFAULT.value,
        simafaImportStatus.simafaImportStatus,
        timeout.time,
        version.version,
        aboutUs,
        NotificationAlertTypesList.DEFAULT.value,
        NotificationMediaTypeList.DEFAULT.value,
        NotificationMediaTypeIds,
        NotificationAlertTypesIds,
        getLogoutReasonDictionary.DEFAULT.value,
        getInvalidLoginReasonDictionary.DEFAULT.value,
        shouldSaveTokensInLocal.DEFAULT.value,
        getMasrafStateDictionary.DEFAULT.value,
        getHighLowStateId.DEFAULT.value,        
        getTarrifCalculationModeDictionary.DEFAULT.value,
        getRequestDraftIds,
        getOfferingIds,
    );
    public static readonly KERMANSHAH = new ActivatedProvince(
        ENActivateProvinceTitle.KERMANSHAH,
        ENURLs.KERMANSHAH,
        ENMapUrls.KERMANSHAH.value,
        ENHasNextBazdid.KERMANSHAH.value,
        reorderableTable.DEFAULT.value,
        defaultAggregateTracks.DEFAULT.value,
        ENMapCenter.KERMANSHAH.value,
        BrowserVersions.DEFAULT.value,
        ENYears.DEFAULT.value,
        getDeleteDictionary.DEFAULT.value,
        ENHasCancelableSpinner.DEFAULT.value,
        simafaImportStatus.simafaImportStatus,
        timeout.time,
        version.version,
        aboutUs,
        NotificationAlertTypesList.DEFAULT.value,
        NotificationMediaTypeList.DEFAULT.value,
        NotificationMediaTypeIds,
        NotificationAlertTypesIds,
        getLogoutReasonDictionary.DEFAULT.value,
        getInvalidLoginReasonDictionary.DEFAULT.value,
        shouldSaveTokensInLocal.DEFAULT.value,
        getMasrafStateDictionary.DEFAULT.value,
        getHighLowStateId.DEFAULT.value,        
        getTarrifCalculationModeDictionary.DEFAULT.value,
        getRequestDraftIds,
        getOfferingIds,
    );
    // ZONE 6 TEHRAN
    public static readonly REY = new ActivatedProvince(
        ENActivateProvinceTitle.REY,
        ENURLs.REY,
        ENMapUrls.REY.value,
        ENHasNextBazdid.REY.value,
        reorderableTable.DEFAULT.value,
        defaultAggregateTracks.DEFAULT.value,
        ENMapCenter.REY.value,
        BrowserVersions.DEFAULT.value,
        ENYears.DEFAULT.value,
        getDeleteDictionary.DEFAULT.value,
        ENHasCancelableSpinner.DEFAULT.value,
        simafaImportStatus.simafaImportStatus,
        timeout.time,
        version.version,
        aboutUs,
        NotificationAlertTypesList.DEFAULT.value,
        NotificationMediaTypeList.DEFAULT.value,
        NotificationMediaTypeIds,
        NotificationAlertTypesIds,
        getLogoutReasonDictionary.DEFAULT.value,
        getInvalidLoginReasonDictionary.DEFAULT.value,
        shouldSaveTokensInLocal.DEFAULT.value,
        getMasrafStateDictionary.DEFAULT.value,
        getHighLowStateId.DEFAULT.value,        
        getTarrifCalculationModeDictionary.DEFAULT.value,
        getRequestDraftIds,
        getOfferingIds,
    );
    public static readonly TSW = new ActivatedProvince(
        ENActivateProvinceTitle.TSW,
        ENURLs.TSW,
        ENMapUrls.REY.value,
        ENHasNextBazdid.REY.value,
        reorderableTable.DEFAULT.value,
        defaultAggregateTracks.DEFAULT.value,
        ENMapCenter.TSW.value,
        BrowserVersions.DEFAULT.value,
        ENYears.DEFAULT.value,
        getDeleteDictionary.DEFAULT.value,
        ENHasCancelableSpinner.DEFAULT.value,
        simafaImportStatus.simafaImportStatus,
        timeout.time,
        version.version,
        aboutUs,
        NotificationAlertTypesList.DEFAULT.value,
        NotificationMediaTypeList.DEFAULT.value,
        NotificationMediaTypeIds,
        NotificationAlertTypesIds,
        getLogoutReasonDictionary.DEFAULT.value,
        getInvalidLoginReasonDictionary.DEFAULT.value,
        shouldSaveTokensInLocal.DEFAULT.value,
        getMasrafStateDictionary.DEFAULT.value,
        getHighLowStateId.DEFAULT.value,        
        getTarrifCalculationModeDictionary.DEFAULT.value,
        getRequestDraftIds,
        getOfferingIds,
    );
    public static readonly TEH1 = new ActivatedProvince(
        ENActivateProvinceTitle.TEH1,
        ENURLs.TEH1,
        ENMapUrls.DEFAULT.value,
        ENHasNextBazdid.DEFAULT.value,
        reorderableTable.DEFAULT.value,
        defaultAggregateTracks.DEFAULT.value,
        ENMapCenter.DEFAULT.value,
        BrowserVersions.DEFAULT.value,
        ENYears.DEFAULT.value,
        getDeleteDictionary.DEFAULT.value,
        ENHasCancelableSpinner.DEFAULT.value,
        simafaImportStatus.simafaImportStatus,
        timeout.time,
        version.version,
        aboutUs,
        NotificationAlertTypesList.DEFAULT.value,
        NotificationMediaTypeList.DEFAULT.value,
        NotificationMediaTypeIds,
        NotificationAlertTypesIds,
        getLogoutReasonDictionary.DEFAULT.value,
        getInvalidLoginReasonDictionary.DEFAULT.value,
        shouldSaveTokensInLocal.DEFAULT.value,
        getMasrafStateDictionary.DEFAULT.value,
        getHighLowStateId.DEFAULT.value,        
        getTarrifCalculationModeDictionary.DEFAULT.value,
        getRequestDraftIds,
        getOfferingIds,
    );
    public static readonly TEH5 = new ActivatedProvince(
        ENActivateProvinceTitle.TEH5,
        ENURLs.TEH5,
        ENMapUrls.DEFAULT.value,
        ENHasNextBazdid.DEFAULT.value,
        reorderableTable.DEFAULT.value,
        defaultAggregateTracks.DEFAULT.value,
        ENMapCenter.DEFAULT.value,
        BrowserVersions.DEFAULT.value,
        ENYears.DEFAULT.value,
        getDeleteDictionary.DEFAULT.value,
        ENHasCancelableSpinner.DEFAULT.value,
        simafaImportStatus.simafaImportStatus,
        timeout.time,
        version.version,
        aboutUs,
        NotificationAlertTypesList.DEFAULT.value,
        NotificationMediaTypeList.DEFAULT.value,
        NotificationMediaTypeIds,
        NotificationAlertTypesIds,
        getLogoutReasonDictionary.DEFAULT.value,
        getInvalidLoginReasonDictionary.DEFAULT.value,
        shouldSaveTokensInLocal.DEFAULT.value,
        getMasrafStateDictionary.DEFAULT.value,
        getHighLowStateId.DEFAULT.value,        
        getTarrifCalculationModeDictionary.DEFAULT.value,
        getRequestDraftIds,
        getOfferingIds,
    );

    private constructor(
        public readonly headerProvinceTitle: ENActivateProvinceTitle,
        public readonly API_URL: string,
        public readonly mapUrls: { title: string, url: string }[],
        public readonly hasNextBazdid: boolean,
        public readonly reOrderableTable: boolean,
        public readonly defaultAggregateTracks: boolean,
        public readonly mapCenter: [number, number],
        public readonly browserVersions: {
            Desktop: {
                Chrome: IENV_BROWSER_SETUP,
                Firefox: IENV_BROWSER_SETUP,
                IE: IENV_BROWSER_SETUP,
                opera: IENV_BROWSER_SETUP,
                safari: IENV_BROWSER_SETUP,
            },
            Touch: {
                Chrome: IENV_BROWSER_SETUP,
                Firefox: IENV_BROWSER_SETUP,
                IE: IENV_BROWSER_SETUP,
                opera: IENV_BROWSER_SETUP,
                safari: IENV_BROWSER_SETUP,
            }
        },
        public readonly years: { title: string, value: number }[],
        public readonly getDeleteDictionary: { id: number, title: string }[],
        public readonly hasCancelableSpinner: boolean,
        public readonly simafaImportStatus: { hasSingle: boolean, hasBatch: boolean },
        public readonly timeout: number,
        public readonly version: string,
        public readonly aboutUs: { email: string, tel: string, address: string, coName: string },
        public readonly NotificationAlertTypesList: { title: string, value: number, titleUnicode: string }[],
        public readonly NotificationMediaTypeList: { title: string, value: number, titleUnicode: string }[],
        public readonly NotificationMediaTypeIds: {
            text: number,
            image: number,
            video: number,
            audio: number
        },
        public readonly NotificationAlertTypesIds: {
            confidential: number,
            ordinary: number,
            sensitive: number,
            memory_full: number,
            security: number,
            license: number,
            incorrect_time: number
        },
        public readonly getLogoutReasonDictionary: { id: number, field: string, title: string }[],
        public readonly getInvalidLoginReasonDictionary: { id: number, title: string, field: string }[],
        public readonly shouldSaveTokensInLocal: boolean,
        public readonly getMasrafStateDictionary: {
            id: number,
            title: string,
            titleUnicode: string,
            icon: string,
            className: string,
            value: number
        }[],
        public readonly getHighLowStateId: {
            id: number,
            title: string,
            titleUnicode: string,
            icon: string,
            className: string,
            value: number
        }[],        
        public readonly getTarrifCalculationModeDictionary: { id: number, dynamicId: number, title: string, field: string }[],
        public readonly getRequestDraftIds: {
            requestDraft: number
        },
        public readonly getOfferingIds: {
            offeringId: number
        }
    ) { }
    public getActiveProvince = (provinceName: ENActivateProvinceTitle): any => {
        return ActivatedProvince[provinceName];
    }
}
